services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - pg-network
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8888:80
    networks:
      - pg-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  api:
    container_name: api
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    volumes:
      - ./:/backend
      - /backend/node_modules
    depends_on:
      - db
    ports:
      - 8000:8000
    command: pnpm start:production
  web:
    container_name: web
    build:
      context: ./apps/web
      dockerfile: .//Dockerfile
    volumes:
      - ./:/web
      - /web/node_modules

volumes:
  db:
    driver: local

networks:
  pg-network:
